
version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0.2
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"
    steps:
      - checkout
      - run: ./mvnw $MAVEN_CLI_OPTS -Dvaadin.offline.key=$VAADIN_OFFLINE_KEY -Dvaadin.offlineMode=true clean package -Pproduction -e
      - store_artifacts:
          path: target
          destination: target
  test:
    docker:
      - image: cimg/openjdk:23.0.2
    steps:
      - checkout
      - run: mvn test -e
      - store_artifacts:
          path: reports
          destination: reports

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build