
version: 2
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0.2
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"
    steps:
      - checkout
      - run: mvn $MVN_CLI_OPTS -Dvaadin.offlinekey="eyJraWQiOiI1NDI3NjRlNzAwMDkwOGU2NWRjM2ZjMWRhYmY0ZTJjZDI4OTY2NzU4IiwidHlwIjoiSldUIiwiYWxnIjoiRVM1MTIifQ.eyJhbGxvd2VkUHJvZHVjdHMiOlsidmFhZGluLWNoYXJ0cyIsInZhYWRpbi10ZXN0YmVuY2giLCJ2YWFkaW4tZGVzaWduZXIiLCJ2YWFkaW4tY2hhcnQiLCJ2YWFkaW4tYm9hcmQiLCJ2YWFkaW4tY29uZmlybS1kaWFsb2ciLCJ2YWFkaW4tY29va2llLWNvbnNlbnQiLCJ2YWFkaW4tcmljaC10ZXh0LWVkaXRvciIsInZhYWRpbi1ncmlkLXBybyIsInZhYWRpbi1tYXAiLCJ2YWFkaW4tc3ByZWFkc2hlZXQtZmxvdyIsInZhYWRpbi1jcnVkIiwidmFhZGluLWNsYXNzaWMtY29tcG9uZW50cyIsInZhYWRpbi1wb3J0bGV0IiwidmFhZGluLW9zZ2kiLCJ2YWFkaW4tZHNwdWJsaXNoZXIiLCJmbG93LXBvbHltZXItdGVtcGxhdGUiLCJ2YWFkaW4tY29waWxvdCIsImZsb3ciLCJ2YWFkaW4tZGFzaGJvYXJkIl0sInN1YiI6ImM0MWNmOWRhLThmNzgtNGExMi1hMGE0LTMwODczMDk1M2EwNCIsInZlciI6MSwiaXNzIjoiVmFhZGluIiwiYWxsb3dlZEZlYXR1cmVzIjpbImNlcnRpZmljYXRpb25zIiwic3ByZWFkc2hlZXQiLCJ0ZXN0YmVuY2giLCJkZXNpZ25lciIsImNoYXJ0cyIsImJvYXJkIiwiYXBwc3RhcnRlciIsInByaW1lLXByb2R1Y3RzLTIwMjIxMCIsInZpZGVvdHJhaW5pbmciLCJwcm8tcHJvZHVjdHMtMjAyMjEwIl0sIm1hY2hpbmVfaWQiOm51bGwsInN1YnNjcmlwdGlvbiI6IlZhYWRpbiBQcm8gQ29tbWVyY2lhbCBUcmlhbCIsInN1YnNjcmlwdGlvbktleSI6bnVsbCwibmFtZSI6InRpbnNhZS1naGlsYXkgRW1wdHkiLCJidWlsZF90eXBlcyI6WyJwcm9kdWN0aW9uIl0sImV4cCI6MTc1MDQ2NDAwMCwiaWF0IjoxNzQ2MTkzMjczLCJhY2NvdW50IjoiTWFuYWdlbWVudCBDZW50ZXIgSW5uc2JydWNrIn0.AP2nOwP4rlyjw7qUgq_jYU82RevcnkkkHUA8feaRQ5xeWcySe4T42P21kXCSQaNrMsKyE0PunrDFNmGIDjK1xTCUAbv_mrv2CCW4crFXU3qu5GijHQt-d3FtWEWvIwYIB4PaGwb_9__7YStYE-mv8dY1sqQMySqAQy39pEMp-ykdteE-" clean package -Pproduction -e
      - store_artifacts:
          path: target
          destination: target
    executor:
  test:
    docker:
      - image: cimg/openjdk:23.0.2
    steps:
      - checkout
      - run: mvn test -e
      - store_artifacts:
          path: reports
          destination: reports
    executor:


workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build